package com.github.jaryarbn.minishop.generate;

import com.github.jaryarbn.minishop.generate.Shop;
import com.github.jaryarbn.minishop.generate.ShopExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOP
     *
     * @mbg.generated Thu May 25 21:40:52 CST 2023
     */
    long countByExample(ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOP
     *
     * @mbg.generated Thu May 25 21:40:52 CST 2023
     */
    int deleteByExample(ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOP
     *
     * @mbg.generated Thu May 25 21:40:52 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOP
     *
     * @mbg.generated Thu May 25 21:40:52 CST 2023
     */
    int insert(Shop row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOP
     *
     * @mbg.generated Thu May 25 21:40:52 CST 2023
     */
    int insertSelective(Shop row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOP
     *
     * @mbg.generated Thu May 25 21:40:52 CST 2023
     */
    List<Shop> selectByExample(ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOP
     *
     * @mbg.generated Thu May 25 21:40:52 CST 2023
     */
    Shop selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOP
     *
     * @mbg.generated Thu May 25 21:40:52 CST 2023
     */
    int updateByExampleSelective(@Param("row") Shop row, @Param("example") ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOP
     *
     * @mbg.generated Thu May 25 21:40:52 CST 2023
     */
    int updateByExample(@Param("row") Shop row, @Param("example") ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOP
     *
     * @mbg.generated Thu May 25 21:40:52 CST 2023
     */
    int updateByPrimaryKeySelective(Shop row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOP
     *
     * @mbg.generated Thu May 25 21:40:52 CST 2023
     */
    int updateByPrimaryKey(Shop row);
}